<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<WasmFingerprintAssets>false</WasmFingerprintAssets>
	</PropertyGroup>
	<PropertyGroup>
		<BlazorWebAssemblyLoadAllGlobalizationData>false</BlazorWebAssemblyLoadAllGlobalizationData>
		<InvariantGlobalization>true</InvariantGlobalization>
		<BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
		<PublishTrimmed>true</PublishTrimmed>
		<TrimMode>full</TrimMode>
	</PropertyGroup>
	<ItemGroup>
	  <Content Remove="wwwroot\js\chromeInterop.js" />
	  <Content Remove="wwwroot\js\filescanner.js" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Blazor.BrowserExtension" Version="5.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.*" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.*" PrivateAssets="all" />
	</ItemGroup>
</Project>